name: 'Build and Publish Docker Images'

env:
  # Push main branch only, else just build
  DOCKER_PUSH: ${{ github.ref == 'refs/heads/main' }}

on:
  push:
    branches: [main, develop]
    paths-ignore: [README.md]
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * MON"

jobs:
  build:
    name: 'Build and Publish Docker Images'
    runs-on: ubuntu-latest

    steps:

      # https://github.com/marketplace/actions/checkout
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      # https://github.com/marketplace/actions/docker-setup-qemu
      - name: 'Setup QEMU'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7

      # https://github.com/marketplace/actions/docker-setup-buildx
      - name: 'Setup Docker Buildx'
        uses: docker/setup-buildx-action@v2

      # https://github.com/marketplace/actions/docker-login
      - name: 'Login to Docker Hub'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images

      # .NET 6.0
      - name: 'Build and Push .NET 6.0'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ env.DOCKER_PUSH }}
          tags: |
            ptr727/vscode-server-dotnetcore:6.0
          build-args: |
            LABEL_VERSION=6.0
            INSTALL_VERSION=dotnet-sdk-6.0

      # .NET 7.0
      - name: 'Build and Push .NET 7.0'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ env.DOCKER_PUSH }}
          tags: |
            ptr727/vscode-server-dotnetcore:7.0
          build-args: |
            LABEL_VERSION=7.0
            INSTALL_VERSION=dotnet-sdk-7.0

      # .NET 6.0 and .NET 7.0
      - name: 'Build and Push .NET 6.0 and .NET 7.0'
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: ${{ env.DOCKER_PUSH }}
          tags: |
            ptr727/vscode-server-dotnetcore:latest
            ptr727/vscode-server-dotnetcore:60.70
          build-args: |
            LABEL_VERSION=60.70
            "INSTALL_VERSION=dotnet-sdk-6.0 dotnet-sdk-7.0"
